using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Dovetail;

[Generator(LanguageNames.CSharp)]
internal sealed class ServiceCollectionExtensionsGenerator : IIncrementalGenerator
{
    private const string ServiceCollectionMetadataName = "Microsoft.Extensions.DependencyInjection.IServiceCollection";

    internal const string RegisteredTypesTrackingName = "RegisteredTypes";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var candidates = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => node is TypeDeclarationSyntax { BaseList.Types.Count: > 0 },
                transform: static (ctx, _) => GetCandidate(ctx))
            .Where(static candidate => candidate is not null)
            .Select(static (candidate, _) => candidate!.Value)
            .Collect()
            .WithTrackingName(RegisteredTypesTrackingName);

        var hasServiceCollection = context.CompilationProvider
            .Select(static (compilation, _) => compilation.GetTypeByMetadataName(ServiceCollectionMetadataName) is not null);

        context.RegisterSourceOutput(candidates.Combine(hasServiceCollection), static (spc, data) =>
        {
            var (types, hasServiceCollection) = data;
            if (!hasServiceCollection)
            {
                return;
            }

            var distinctTypes = types.Distinct().ToImmutableArray();
            if (distinctTypes.IsEmpty)
            {
                return;
            }

            spc.AddSource("DovetailServiceCollectionExtensions.g.cs", GenerateSource(distinctTypes));
        });
    }

    private static RegisteredTypeInfo? GetCandidate(GeneratorSyntaxContext context)
    {
        if (context.SemanticModel.GetDeclaredSymbol(context.Node) is not INamedTypeSymbol { TypeKind: TypeKind.Class, IsAbstract: false, Arity: 0 } symbol)
        {
            return null;
        }

        var fullyQualifiedName = symbol.ToDisplayString(PipelineShapeResolver.TypeNameFormat);

        if (PipelineShapeResolver.TryGetSegmentShape(symbol, out _, out _))
        {
            return new RegisteredTypeInfo(fullyQualifiedName, IsPipeline: false);
        }

        if (PipelineShapeResolver.TryGetPipelineShape(symbol, out _, out _))
        {
            return new RegisteredTypeInfo(fullyQualifiedName, IsPipeline: true);
        }

        return null;
    }

    private static string GenerateSource(ImmutableArray<RegisteredTypeInfo> types)
    {
        var builder = new StringBuilder()
            .AppendLine("// <auto-generated/>")
            .AppendLine("#nullable enable")
            .AppendLine()
            .AppendLine("namespace Microsoft.Extensions.DependencyInjection;")
            .AppendLine()
            .AppendLine("public static class DovetailServiceCollectionExtensions")
            .AppendLine("{")
            .AppendLine("    /// <summary>Registers every Dovetail pipeline segment and pipeline found in this compilation as transient services.</summary>")
            .AppendLine("    public static IServiceCollection AddPipelines(this IServiceCollection services)")
            .AppendLine("    {");

        foreach (var segment in types.Where(static t => !t.IsPipeline).OrderBy(static t => t.FullyQualifiedName, StringComparer.Ordinal))
        {
            builder.AppendLine($"        services.AddTransient<{segment.FullyQualifiedName}>();");
        }

        foreach (var pipeline in types.Where(static t => t.IsPipeline).OrderBy(static t => t.FullyQualifiedName, StringComparer.Ordinal))
        {
            builder.AppendLine($"        services.AddTransient<{pipeline.FullyQualifiedName}>();");
        }

        builder.AppendLine("        return services;")
            .AppendLine("    }")
            .AppendLine("}");

        return builder.ToString();
    }
}
